theme: jekyll-theme-hacker
# Site Information
title: zhlyr
description: \nA library for handling music, fetching music lyrics, and predicting the name of a song from a short audio snippet.
favicon: "/favicon.png"
source: /

url: https://github.com/Gaoc3
baseurl: /zhlyr

languages: [ar, en]

fonts:
  regular: "16px"
  large: "18px"





