remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: zhlyr
description: Python library for working with images
github:
  zip_url: http://example.com/download.zip
  another_url: http://example.com/download.zip
first_name: zhan
middle_name:
last_name: ibrahim
